/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcceptedDeliveryWithTracking {
  'status' : string,
  'trackingCode' : string,
  'requestId' : string,
  'riderPrincipal' : Principal,
  'createdAt' : bigint,
  'senderPrincipal' : Principal,
  'routeId' : string,
  'trackingEntries' : Array<TrackingEntry>,
  'packageId' : string,
}
export type AdminResult = { 'ok' : string } |
  { 'err' : string };
export interface Alert {
  'id' : string,
  'createdAt' : bigint,
  'targetPrice' : number,
  'isActive' : boolean,
  'assetType' : string,
  'isTriggered' : boolean,
  'symbol' : string,
  'condition' : string,
}
export interface CryptoQuote {
  'name' : string,
  'changesPercentage' : number,
  'price' : number,
  'symbol' : string,
}
export interface DeliveryRequest {
  'status' : string,
  'requestId' : string,
  'riderPrincipal' : Principal,
  'createdAt' : bigint,
  'senderPrincipal' : Principal,
  'routeId' : string,
  'packageId' : string,
}
export interface ForexRate { 'rate' : number, 'symbol' : string }
export interface MarketData {
  'forex' : Array<ForexRate>,
  'stocks' : Array<StockQuote>,
  'lastUpdated' : bigint,
  'crypto' : Array<CryptoQuote>,
  'success' : boolean,
}
export type MoveResult = { 'ok' : string } |
  { 'err' : string };
export interface NewsArticle {
  'url' : string,
  'title' : string,
  'source' : string,
  'urlToImage' : string,
  'publishedAt' : string,
  'description' : string,
}
export interface NewsData {
  'articles' : Array<NewsArticle>,
  'lastUpdated' : bigint,
  'success' : boolean,
}
export interface Package {
  'createdAt' : bigint,
  'size' : string,
  'description' : string,
  'destinationCity' : string,
  'weightKg' : number,
  'senderPrincipal' : Principal,
  'destinationCountry' : string,
  'packageId' : string,
  'pickupLocation' : string,
}
export interface RequestWithPackage {
  'status' : string,
  'requestId' : string,
  'createdAt' : bigint,
  'size' : string,
  'description' : string,
  'destinationCity' : string,
  'weightKg' : number,
  'senderPrincipal' : Principal,
  'routeId' : string,
  'destinationCountry' : string,
  'packageId' : string,
  'pickupLocation' : string,
}
export interface RiderRoute {
  'vehicleType' : string,
  'riderPrincipal' : Principal,
  'departureCountry' : string,
  'departureCity' : string,
  'createdAt' : bigint,
  'destinationCity' : string,
  'routeId' : string,
  'travelDate' : string,
  'destinationCountry' : string,
  'cargoSpace' : string,
}
export interface RiderVerification {
  'riderPrincipal' : Principal,
  'vehicleRegDocUrl' : [] | [string],
  'licenseDocUrl' : [] | [string],
  'nationalIdDocUrl' : [] | [string],
  'licenseType' : string,
  'licenseNumber' : string,
  'vehicleRegistrationNumber' : string,
  'verifiedAt' : bigint,
  'nationalIdNumber' : string,
}
export interface RiderVerificationWithStatus {
  'status' : VerificationStatus,
  'riderPrincipal' : Principal,
  'vehicleRegDocUrl' : [] | [string],
  'licenseDocUrl' : [] | [string],
  'nationalIdDocUrl' : [] | [string],
  'licenseType' : string,
  'licenseNumber' : string,
  'vehicleRegistrationNumber' : string,
  'verifiedAt' : bigint,
  'nationalIdNumber' : string,
}
export interface SavingsGoal {
  'id' : string,
  'isCompleted' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'targetAmount' : number,
  'currency' : string,
  'lockedAmount' : number,
}
export type SavingsGoalResult = { 'ok' : SavingsGoal } |
  { 'err' : string };
export type SendMoneyResult = {
    'ok' : {
      'txId' : string,
      'reference' : string,
      'currency' : string,
      'timestamp' : string,
      'amount' : number,
      'recipientId' : string,
    }
  } |
  { 'err' : string };
export interface SenderVerification {
  'nationalIdDocUrl' : [] | [string],
  'senderPrincipal' : Principal,
  'phoneNumber' : string,
  'verifiedAt' : bigint,
  'nationalIdNumber' : string,
}
export interface SenderVerificationWithStatus {
  'status' : VerificationStatus,
  'nationalIdDocUrl' : [] | [string],
  'senderPrincipal' : Principal,
  'phoneNumber' : string,
  'verifiedAt' : bigint,
  'nationalIdNumber' : string,
}
export interface ShipmentTracking {
  'trackingCode' : string,
  'requestId' : string,
  'entries' : Array<TrackingEntry>,
  'currentStatus' : string,
  'packageId' : string,
}
export interface StockQuote {
  'name' : string,
  'changesPercentage' : number,
  'price' : number,
  'symbol' : string,
}
export interface TrackingEntry { 'status' : string, 'timestamp' : bigint }
export type UnlockResult = { 'ok' : number } |
  { 'err' : string };
export interface UserProfile {
  'hideBalance' : boolean,
  'hideTransactions' : boolean,
  'displayName' : string,
  'preferredCurrency' : string,
  'language' : string,
}
export type VerificationStatus = { 'Approved' : { 'notes' : string } } |
  { 'Rejected' : { 'reason' : string } } |
  { 'Pending' : null };
export interface VirtualAccount {
  'expiresAt' : string,
  'reference' : string,
  'bankName' : string,
  'accountName' : string,
  'accountNumber' : string,
}
export type VirtualAccountResult = { 'ok' : VirtualAccount } |
  { 'err' : string };
export interface WalletBalance { 'currency' : string, 'amount' : number }
export interface WalletTransaction {
  'id' : string,
  'status' : string,
  'date' : string,
  'desc' : string,
  'currency' : string,
  'txType' : string,
  'amount' : number,
}
export interface YouTubeVideo {
  'title' : string,
  'channelTitle' : string,
  'thumbnail' : string,
  'videoId' : string,
}
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], AdminResult>,
  'addAlert' : ActorMethod<[string, string, string, number], Alert>,
  'addToSavingsGoal' : ActorMethod<[string, number], SavingsGoalResult>,
  'addWalletTransaction' : ActorMethod<
    [string, string, number, string, string, string],
    WalletTransaction
  >,
  'approveRiderVerification' : ActorMethod<[Principal, string], AdminResult>,
  'approveSenderVerification' : ActorMethod<[Principal, string], AdminResult>,
  'clearAlertTriggered' : ActorMethod<[string], boolean>,
  'createSavingsGoal' : ActorMethod<
    [string, number, number, string],
    SavingsGoalResult
  >,
  'createVirtualAccount' : ActorMethod<[string], VirtualAccountResult>,
  'deleteAlert' : ActorMethod<[string], boolean>,
  'deleteRoute' : ActorMethod<[string], MoveResult>,
  'getAcceptedDeliveries' : ActorMethod<[], Array<DeliveryRequest>>,
  'getAcceptedDeliveriesWithTracking' : ActorMethod<
    [],
    Array<AcceptedDeliveryWithTracking>
  >,
  'getAdminList' : ActorMethod<[], Array<Principal>>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllRiderVerifications' : ActorMethod<
    [],
    Array<RiderVerificationWithStatus>
  >,
  'getAllRoutes' : ActorMethod<[], Array<RiderRoute>>,
  'getAllSenderVerifications' : ActorMethod<
    [],
    Array<SenderVerificationWithStatus>
  >,
  'getHistoricalForex' : ActorMethod<[string], Array<number>>,
  'getHistoricalPrices' : ActorMethod<[string], Array<number>>,
  'getIncomingRequests' : ActorMethod<[], Array<RequestWithPackage>>,
  'getMarketData' : ActorMethod<[], MarketData>,
  'getMatchedRiders' : ActorMethod<[string, string], Array<RiderRoute>>,
  'getNewsData' : ActorMethod<[], NewsData>,
  'getRiderRoutes' : ActorMethod<[], Array<RiderRoute>>,
  'getRiderVerification' : ActorMethod<[], [] | [RiderVerification]>,
  'getSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'getSenderPackages' : ActorMethod<[], Array<Package>>,
  'getSenderRequests' : ActorMethod<[], Array<DeliveryRequest>>,
  'getSenderTrackings' : ActorMethod<[], Array<ShipmentTracking>>,
  'getSenderVerification' : ActorMethod<[], [] | [SenderVerification]>,
  'getTrackingByCode' : ActorMethod<[string], [] | [ShipmentTracking]>,
  'getTrackingByRequestId' : ActorMethod<[string], [] | [ShipmentTracking]>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getVirtualAccount' : ActorMethod<[], [] | [VirtualAccount]>,
  'getWalletBalance' : ActorMethod<[string], number>,
  'getWalletBalances' : ActorMethod<[], Array<WalletBalance>>,
  'getWalletTransactions' : ActorMethod<[], Array<WalletTransaction>>,
  'getYouTubeVideos' : ActorMethod<[], Array<YouTubeVideo>>,
  'getYouTubeVideosByQuery' : ActorMethod<[string], Array<YouTubeVideo>>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'markAlertTriggered' : ActorMethod<[string], boolean>,
  'postPackage' : ActorMethod<
    [string, string, string, string, number, string],
    MoveResult
  >,
  'recordMovePayment' : ActorMethod<
    [string, string, string, number, string, string, string, string],
    MoveResult
  >,
  'refreshVirtualAccount' : ActorMethod<[string], VirtualAccountResult>,
  'registerRoute' : ActorMethod<
    [string, string, string, string, string, string, string],
    MoveResult
  >,
  'rejectRiderVerification' : ActorMethod<[Principal, string], AdminResult>,
  'rejectSenderVerification' : ActorMethod<[Principal, string], AdminResult>,
  'removeAdmin' : ActorMethod<[Principal], AdminResult>,
  'respondToRequest' : ActorMethod<[string, boolean], MoveResult>,
  'saveUserProfile' : ActorMethod<
    [string, string, string, boolean, boolean],
    UserProfile
  >,
  'sendDeliveryRequest' : ActorMethod<[string, string, string], MoveResult>,
  'sendMoney' : ActorMethod<[string, number, string, string], SendMoneyResult>,
  'submitRiderVerification' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    MoveResult
  >,
  'submitSenderVerification' : ActorMethod<
    [string, string, [] | [string]],
    MoveResult
  >,
  'unlockSavingsGoal' : ActorMethod<[string], UnlockResult>,
  'updateAlert' : ActorMethod<[string, boolean], boolean>,
  'updateRoute' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    MoveResult
  >,
  'updateShipmentStatus' : ActorMethod<[string, string], MoveResult>,
  'updateWalletBalance' : ActorMethod<[string, number], WalletBalance>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];