/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Alert = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Nat,
  'targetPrice' : IDL.Float64,
  'isActive' : IDL.Bool,
  'assetType' : IDL.Text,
  'isTriggered' : IDL.Bool,
  'symbol' : IDL.Text,
  'condition' : IDL.Text,
});
export const SavingsGoal = IDL.Record({
  'id' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'targetAmount' : IDL.Float64,
  'currency' : IDL.Text,
  'lockedAmount' : IDL.Float64,
});
export const SavingsGoalResult = IDL.Variant({
  'ok' : SavingsGoal,
  'err' : IDL.Text,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'desc' : IDL.Text,
  'currency' : IDL.Text,
  'txType' : IDL.Text,
  'amount' : IDL.Float64,
});
export const VirtualAccount = IDL.Record({
  'expiresAt' : IDL.Text,
  'reference' : IDL.Text,
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const VirtualAccountResult = IDL.Variant({
  'ok' : VirtualAccount,
  'err' : IDL.Text,
});
export const MoveResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const DeliveryRequest = IDL.Record({
  'status' : IDL.Text,
  'requestId' : IDL.Text,
  'riderPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'senderPrincipal' : IDL.Principal,
  'routeId' : IDL.Text,
  'packageId' : IDL.Text,
});
export const TrackingEntry = IDL.Record({
  'status' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AcceptedDeliveryWithTracking = IDL.Record({
  'status' : IDL.Text,
  'trackingCode' : IDL.Text,
  'requestId' : IDL.Text,
  'riderPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'senderPrincipal' : IDL.Principal,
  'routeId' : IDL.Text,
  'trackingEntries' : IDL.Vec(TrackingEntry),
  'packageId' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'Approved' : IDL.Record({ 'notes' : IDL.Text }),
  'Rejected' : IDL.Record({ 'reason' : IDL.Text }),
  'Pending' : IDL.Null,
});
export const RiderVerificationWithStatus = IDL.Record({
  'status' : VerificationStatus,
  'riderPrincipal' : IDL.Principal,
  'vehicleRegDocUrl' : IDL.Opt(IDL.Text),
  'licenseDocUrl' : IDL.Opt(IDL.Text),
  'nationalIdDocUrl' : IDL.Opt(IDL.Text),
  'licenseType' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'vehicleRegistrationNumber' : IDL.Text,
  'verifiedAt' : IDL.Int,
  'nationalIdNumber' : IDL.Text,
});
export const RiderRoute = IDL.Record({
  'vehicleType' : IDL.Text,
  'riderPrincipal' : IDL.Principal,
  'departureCountry' : IDL.Text,
  'departureCity' : IDL.Text,
  'createdAt' : IDL.Int,
  'destinationCity' : IDL.Text,
  'routeId' : IDL.Text,
  'travelDate' : IDL.Text,
  'destinationCountry' : IDL.Text,
  'cargoSpace' : IDL.Text,
});
export const SenderVerificationWithStatus = IDL.Record({
  'status' : VerificationStatus,
  'nationalIdDocUrl' : IDL.Opt(IDL.Text),
  'senderPrincipal' : IDL.Principal,
  'phoneNumber' : IDL.Text,
  'verifiedAt' : IDL.Int,
  'nationalIdNumber' : IDL.Text,
});
export const RequestWithPackage = IDL.Record({
  'status' : IDL.Text,
  'requestId' : IDL.Text,
  'createdAt' : IDL.Int,
  'size' : IDL.Text,
  'description' : IDL.Text,
  'destinationCity' : IDL.Text,
  'weightKg' : IDL.Float64,
  'senderPrincipal' : IDL.Principal,
  'routeId' : IDL.Text,
  'destinationCountry' : IDL.Text,
  'packageId' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const ForexRate = IDL.Record({
  'rate' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const StockQuote = IDL.Record({
  'name' : IDL.Text,
  'changesPercentage' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const CryptoQuote = IDL.Record({
  'name' : IDL.Text,
  'changesPercentage' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const MarketData = IDL.Record({
  'forex' : IDL.Vec(ForexRate),
  'stocks' : IDL.Vec(StockQuote),
  'lastUpdated' : IDL.Nat,
  'crypto' : IDL.Vec(CryptoQuote),
  'success' : IDL.Bool,
});
export const NewsArticle = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'urlToImage' : IDL.Text,
  'publishedAt' : IDL.Text,
  'description' : IDL.Text,
});
export const NewsData = IDL.Record({
  'articles' : IDL.Vec(NewsArticle),
  'lastUpdated' : IDL.Nat,
  'success' : IDL.Bool,
});
export const RiderVerification = IDL.Record({
  'riderPrincipal' : IDL.Principal,
  'vehicleRegDocUrl' : IDL.Opt(IDL.Text),
  'licenseDocUrl' : IDL.Opt(IDL.Text),
  'nationalIdDocUrl' : IDL.Opt(IDL.Text),
  'licenseType' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'vehicleRegistrationNumber' : IDL.Text,
  'verifiedAt' : IDL.Int,
  'nationalIdNumber' : IDL.Text,
});
export const Package = IDL.Record({
  'createdAt' : IDL.Int,
  'size' : IDL.Text,
  'description' : IDL.Text,
  'destinationCity' : IDL.Text,
  'weightKg' : IDL.Float64,
  'senderPrincipal' : IDL.Principal,
  'destinationCountry' : IDL.Text,
  'packageId' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const ShipmentTracking = IDL.Record({
  'trackingCode' : IDL.Text,
  'requestId' : IDL.Text,
  'entries' : IDL.Vec(TrackingEntry),
  'currentStatus' : IDL.Text,
  'packageId' : IDL.Text,
});
export const SenderVerification = IDL.Record({
  'nationalIdDocUrl' : IDL.Opt(IDL.Text),
  'senderPrincipal' : IDL.Principal,
  'phoneNumber' : IDL.Text,
  'verifiedAt' : IDL.Int,
  'nationalIdNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'hideBalance' : IDL.Bool,
  'hideTransactions' : IDL.Bool,
  'displayName' : IDL.Text,
  'preferredCurrency' : IDL.Text,
  'language' : IDL.Text,
});
export const WalletBalance = IDL.Record({
  'currency' : IDL.Text,
  'amount' : IDL.Float64,
});
export const YouTubeVideo = IDL.Record({
  'title' : IDL.Text,
  'channelTitle' : IDL.Text,
  'thumbnail' : IDL.Text,
  'videoId' : IDL.Text,
});
export const SendMoneyResult = IDL.Variant({
  'ok' : IDL.Record({
    'txId' : IDL.Text,
    'reference' : IDL.Text,
    'currency' : IDL.Text,
    'timestamp' : IDL.Text,
    'amount' : IDL.Float64,
    'recipientId' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const UnlockResult = IDL.Variant({
  'ok' : IDL.Float64,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [AdminResult], []),
  'addAlert' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [Alert],
      [],
    ),
  'addToSavingsGoal' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [SavingsGoalResult],
      [],
    ),
  'addWalletTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [WalletTransaction],
      [],
    ),
  'approveRiderVerification' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [AdminResult],
      [],
    ),
  'approveSenderVerification' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [AdminResult],
      [],
    ),
  'clearAlertTriggered' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createSavingsGoal' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [SavingsGoalResult],
      [],
    ),
  'createVirtualAccount' : IDL.Func([IDL.Text], [VirtualAccountResult], []),
  'deleteAlert' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteRoute' : IDL.Func([IDL.Text], [MoveResult], []),
  'getAcceptedDeliveries' : IDL.Func([], [IDL.Vec(DeliveryRequest)], ['query']),
  'getAcceptedDeliveriesWithTracking' : IDL.Func(
      [],
      [IDL.Vec(AcceptedDeliveryWithTracking)],
      ['query'],
    ),
  'getAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], []),
  'getAllRiderVerifications' : IDL.Func(
      [],
      [IDL.Vec(RiderVerificationWithStatus)],
      ['query'],
    ),
  'getAllRoutes' : IDL.Func([], [IDL.Vec(RiderRoute)], ['query']),
  'getAllSenderVerifications' : IDL.Func(
      [],
      [IDL.Vec(SenderVerificationWithStatus)],
      ['query'],
    ),
  'getHistoricalForex' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Float64)], []),
  'getHistoricalPrices' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Float64)], []),
  'getIncomingRequests' : IDL.Func(
      [],
      [IDL.Vec(RequestWithPackage)],
      ['query'],
    ),
  'getMarketData' : IDL.Func([], [MarketData], []),
  'getMatchedRiders' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(RiderRoute)],
      ['query'],
    ),
  'getNewsData' : IDL.Func([], [NewsData], []),
  'getNotificationSubscription' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getRiderRoutes' : IDL.Func([], [IDL.Vec(RiderRoute)], ['query']),
  'getRiderVerification' : IDL.Func(
      [],
      [IDL.Opt(RiderVerification)],
      ['query'],
    ),
  'getSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
  'getSenderPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getSenderRequests' : IDL.Func([], [IDL.Vec(DeliveryRequest)], ['query']),
  'getSenderTrackings' : IDL.Func([], [IDL.Vec(ShipmentTracking)], ['query']),
  'getSenderVerification' : IDL.Func(
      [],
      [IDL.Opt(SenderVerification)],
      ['query'],
    ),
  'getTrackingByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ShipmentTracking)],
      ['query'],
    ),
  'getTrackingByRequestId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ShipmentTracking)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getVirtualAccount' : IDL.Func([], [IDL.Opt(VirtualAccount)], ['query']),
  'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getWalletBalances' : IDL.Func([], [IDL.Vec(WalletBalance)], ['query']),
  'getWalletTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getYouTubeVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], []),
  'getYouTubeVideosByQuery' : IDL.Func([IDL.Text], [IDL.Vec(YouTubeVideo)], []),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'markAlertTriggered' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'postPackage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [MoveResult],
      [],
    ),
  'recordMovePayment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [MoveResult],
      [],
    ),
  'refreshVirtualAccount' : IDL.Func([IDL.Text], [VirtualAccountResult], []),
  'registerRoute' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MoveResult],
      [],
    ),
  'rejectRiderVerification' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [AdminResult],
      [],
    ),
  'rejectSenderVerification' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [AdminResult],
      [],
    ),
  'removeAdmin' : IDL.Func([IDL.Principal], [AdminResult], []),
  'respondToRequest' : IDL.Func([IDL.Text, IDL.Bool], [MoveResult], []),
  'saveNotificationSubscription' : IDL.Func([IDL.Text], [], []),
  'saveUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [UserProfile],
      [],
    ),
  'sendDeliveryRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [MoveResult],
      [],
    ),
  'sendMoney' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [SendMoneyResult],
      [],
    ),
  'submitRiderVerification' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [MoveResult],
      [],
    ),
  'submitSenderVerification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [MoveResult],
      [],
    ),
  'unlockSavingsGoal' : IDL.Func([IDL.Text], [UnlockResult], []),
  'updateAlert' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'updateRoute' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [MoveResult],
      [],
    ),
  'updateShipmentStatus' : IDL.Func([IDL.Text, IDL.Text], [MoveResult], []),
  'updateWalletBalance' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [WalletBalance],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Alert = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Nat,
    'targetPrice' : IDL.Float64,
    'isActive' : IDL.Bool,
    'assetType' : IDL.Text,
    'isTriggered' : IDL.Bool,
    'symbol' : IDL.Text,
    'condition' : IDL.Text,
  });
  const SavingsGoal = IDL.Record({
    'id' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'targetAmount' : IDL.Float64,
    'currency' : IDL.Text,
    'lockedAmount' : IDL.Float64,
  });
  const SavingsGoalResult = IDL.Variant({
    'ok' : SavingsGoal,
    'err' : IDL.Text,
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'desc' : IDL.Text,
    'currency' : IDL.Text,
    'txType' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const VirtualAccount = IDL.Record({
    'expiresAt' : IDL.Text,
    'reference' : IDL.Text,
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const VirtualAccountResult = IDL.Variant({
    'ok' : VirtualAccount,
    'err' : IDL.Text,
  });
  const MoveResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const DeliveryRequest = IDL.Record({
    'status' : IDL.Text,
    'requestId' : IDL.Text,
    'riderPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'senderPrincipal' : IDL.Principal,
    'routeId' : IDL.Text,
    'packageId' : IDL.Text,
  });
  const TrackingEntry = IDL.Record({
    'status' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AcceptedDeliveryWithTracking = IDL.Record({
    'status' : IDL.Text,
    'trackingCode' : IDL.Text,
    'requestId' : IDL.Text,
    'riderPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'senderPrincipal' : IDL.Principal,
    'routeId' : IDL.Text,
    'trackingEntries' : IDL.Vec(TrackingEntry),
    'packageId' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'Approved' : IDL.Record({ 'notes' : IDL.Text }),
    'Rejected' : IDL.Record({ 'reason' : IDL.Text }),
    'Pending' : IDL.Null,
  });
  const RiderVerificationWithStatus = IDL.Record({
    'status' : VerificationStatus,
    'riderPrincipal' : IDL.Principal,
    'vehicleRegDocUrl' : IDL.Opt(IDL.Text),
    'licenseDocUrl' : IDL.Opt(IDL.Text),
    'nationalIdDocUrl' : IDL.Opt(IDL.Text),
    'licenseType' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'vehicleRegistrationNumber' : IDL.Text,
    'verifiedAt' : IDL.Int,
    'nationalIdNumber' : IDL.Text,
  });
  const RiderRoute = IDL.Record({
    'vehicleType' : IDL.Text,
    'riderPrincipal' : IDL.Principal,
    'departureCountry' : IDL.Text,
    'departureCity' : IDL.Text,
    'createdAt' : IDL.Int,
    'destinationCity' : IDL.Text,
    'routeId' : IDL.Text,
    'travelDate' : IDL.Text,
    'destinationCountry' : IDL.Text,
    'cargoSpace' : IDL.Text,
  });
  const SenderVerificationWithStatus = IDL.Record({
    'status' : VerificationStatus,
    'nationalIdDocUrl' : IDL.Opt(IDL.Text),
    'senderPrincipal' : IDL.Principal,
    'phoneNumber' : IDL.Text,
    'verifiedAt' : IDL.Int,
    'nationalIdNumber' : IDL.Text,
  });
  const RequestWithPackage = IDL.Record({
    'status' : IDL.Text,
    'requestId' : IDL.Text,
    'createdAt' : IDL.Int,
    'size' : IDL.Text,
    'description' : IDL.Text,
    'destinationCity' : IDL.Text,
    'weightKg' : IDL.Float64,
    'senderPrincipal' : IDL.Principal,
    'routeId' : IDL.Text,
    'destinationCountry' : IDL.Text,
    'packageId' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const ForexRate = IDL.Record({ 'rate' : IDL.Float64, 'symbol' : IDL.Text });
  const StockQuote = IDL.Record({
    'name' : IDL.Text,
    'changesPercentage' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const CryptoQuote = IDL.Record({
    'name' : IDL.Text,
    'changesPercentage' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const MarketData = IDL.Record({
    'forex' : IDL.Vec(ForexRate),
    'stocks' : IDL.Vec(StockQuote),
    'lastUpdated' : IDL.Nat,
    'crypto' : IDL.Vec(CryptoQuote),
    'success' : IDL.Bool,
  });
  const NewsArticle = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'urlToImage' : IDL.Text,
    'publishedAt' : IDL.Text,
    'description' : IDL.Text,
  });
  const NewsData = IDL.Record({
    'articles' : IDL.Vec(NewsArticle),
    'lastUpdated' : IDL.Nat,
    'success' : IDL.Bool,
  });
  const RiderVerification = IDL.Record({
    'riderPrincipal' : IDL.Principal,
    'vehicleRegDocUrl' : IDL.Opt(IDL.Text),
    'licenseDocUrl' : IDL.Opt(IDL.Text),
    'nationalIdDocUrl' : IDL.Opt(IDL.Text),
    'licenseType' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'vehicleRegistrationNumber' : IDL.Text,
    'verifiedAt' : IDL.Int,
    'nationalIdNumber' : IDL.Text,
  });
  const Package = IDL.Record({
    'createdAt' : IDL.Int,
    'size' : IDL.Text,
    'description' : IDL.Text,
    'destinationCity' : IDL.Text,
    'weightKg' : IDL.Float64,
    'senderPrincipal' : IDL.Principal,
    'destinationCountry' : IDL.Text,
    'packageId' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const ShipmentTracking = IDL.Record({
    'trackingCode' : IDL.Text,
    'requestId' : IDL.Text,
    'entries' : IDL.Vec(TrackingEntry),
    'currentStatus' : IDL.Text,
    'packageId' : IDL.Text,
  });
  const SenderVerification = IDL.Record({
    'nationalIdDocUrl' : IDL.Opt(IDL.Text),
    'senderPrincipal' : IDL.Principal,
    'phoneNumber' : IDL.Text,
    'verifiedAt' : IDL.Int,
    'nationalIdNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'hideBalance' : IDL.Bool,
    'hideTransactions' : IDL.Bool,
    'displayName' : IDL.Text,
    'preferredCurrency' : IDL.Text,
    'language' : IDL.Text,
  });
  const WalletBalance = IDL.Record({
    'currency' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const YouTubeVideo = IDL.Record({
    'title' : IDL.Text,
    'channelTitle' : IDL.Text,
    'thumbnail' : IDL.Text,
    'videoId' : IDL.Text,
  });
  const SendMoneyResult = IDL.Variant({
    'ok' : IDL.Record({
      'txId' : IDL.Text,
      'reference' : IDL.Text,
      'currency' : IDL.Text,
      'timestamp' : IDL.Text,
      'amount' : IDL.Float64,
      'recipientId' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const UnlockResult = IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [AdminResult], []),
    'addAlert' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [Alert],
        [],
      ),
    'addToSavingsGoal' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [SavingsGoalResult],
        [],
      ),
    'addWalletTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [WalletTransaction],
        [],
      ),
    'approveRiderVerification' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [AdminResult],
        [],
      ),
    'approveSenderVerification' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [AdminResult],
        [],
      ),
    'clearAlertTriggered' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createSavingsGoal' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [SavingsGoalResult],
        [],
      ),
    'createVirtualAccount' : IDL.Func([IDL.Text], [VirtualAccountResult], []),
    'deleteAlert' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteRoute' : IDL.Func([IDL.Text], [MoveResult], []),
    'getAcceptedDeliveries' : IDL.Func(
        [],
        [IDL.Vec(DeliveryRequest)],
        ['query'],
      ),
    'getAcceptedDeliveriesWithTracking' : IDL.Func(
        [],
        [IDL.Vec(AcceptedDeliveryWithTracking)],
        ['query'],
      ),
    'getAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], []),
    'getAllRiderVerifications' : IDL.Func(
        [],
        [IDL.Vec(RiderVerificationWithStatus)],
        ['query'],
      ),
    'getAllRoutes' : IDL.Func([], [IDL.Vec(RiderRoute)], ['query']),
    'getAllSenderVerifications' : IDL.Func(
        [],
        [IDL.Vec(SenderVerificationWithStatus)],
        ['query'],
      ),
    'getHistoricalForex' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Float64)], []),
    'getHistoricalPrices' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Float64)], []),
    'getIncomingRequests' : IDL.Func(
        [],
        [IDL.Vec(RequestWithPackage)],
        ['query'],
      ),
    'getMarketData' : IDL.Func([], [MarketData], []),
    'getMatchedRiders' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(RiderRoute)],
        ['query'],
      ),
    'getNewsData' : IDL.Func([], [NewsData], []),
    'getNotificationSubscription' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getRiderRoutes' : IDL.Func([], [IDL.Vec(RiderRoute)], ['query']),
    'getRiderVerification' : IDL.Func(
        [],
        [IDL.Opt(RiderVerification)],
        ['query'],
      ),
    'getSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
    'getSenderPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getSenderRequests' : IDL.Func([], [IDL.Vec(DeliveryRequest)], ['query']),
    'getSenderTrackings' : IDL.Func([], [IDL.Vec(ShipmentTracking)], ['query']),
    'getSenderVerification' : IDL.Func(
        [],
        [IDL.Opt(SenderVerification)],
        ['query'],
      ),
    'getTrackingByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ShipmentTracking)],
        ['query'],
      ),
    'getTrackingByRequestId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ShipmentTracking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getVirtualAccount' : IDL.Func([], [IDL.Opt(VirtualAccount)], ['query']),
    'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getWalletBalances' : IDL.Func([], [IDL.Vec(WalletBalance)], ['query']),
    'getWalletTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getYouTubeVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], []),
    'getYouTubeVideosByQuery' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(YouTubeVideo)],
        [],
      ),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'markAlertTriggered' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'postPackage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [MoveResult],
        [],
      ),
    'recordMovePayment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [MoveResult],
        [],
      ),
    'refreshVirtualAccount' : IDL.Func([IDL.Text], [VirtualAccountResult], []),
    'registerRoute' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [MoveResult],
        [],
      ),
    'rejectRiderVerification' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [AdminResult],
        [],
      ),
    'rejectSenderVerification' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [AdminResult],
        [],
      ),
    'removeAdmin' : IDL.Func([IDL.Principal], [AdminResult], []),
    'respondToRequest' : IDL.Func([IDL.Text, IDL.Bool], [MoveResult], []),
    'saveNotificationSubscription' : IDL.Func([IDL.Text], [], []),
    'saveUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [UserProfile],
        [],
      ),
    'sendDeliveryRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [MoveResult],
        [],
      ),
    'sendMoney' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [SendMoneyResult],
        [],
      ),
    'submitRiderVerification' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [MoveResult],
        [],
      ),
    'submitSenderVerification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [MoveResult],
        [],
      ),
    'unlockSavingsGoal' : IDL.Func([IDL.Text], [UnlockResult], []),
    'updateAlert' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'updateRoute' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [MoveResult],
        [],
      ),
    'updateShipmentStatus' : IDL.Func([IDL.Text, IDL.Text], [MoveResult], []),
    'updateWalletBalance' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [WalletBalance],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };