/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface StockQuote {
  symbol: string;
  name: string;
  price: number;
  changesPercentage: number;
}

export interface ForexRate {
  symbol: string;
  rate: number;
}

export interface CryptoQuote {
  symbol: string;
  name: string;
  price: number;
  changesPercentage: number;
}

export interface MarketData {
  stocks: StockQuote[];
  forex: ForexRate[];
  crypto: CryptoQuote[];
  lastUpdated: bigint;
  success: boolean;
}

export interface NewsArticle {
  title: string;
  source: string;
  url: string;
  urlToImage: string;
  publishedAt: string;
  description: string;
}

export interface NewsData {
  articles: NewsArticle[];
  lastUpdated: bigint;
  success: boolean;
}

export interface _SERVICE {
  getMarketData: ActorMethod<[], MarketData>;
  getNewsData: ActorMethod<[], NewsData>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
